import "./globals.css";
import Image from "next/image";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Menu from "./components/Menu";
import Link from "next/link";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Treinador Abner",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${ubuntu.className}`}>
      <body>
        <div className="bg-black w-full bg-top bg-no-repeat lg:bg-none fixed z-50 top-0">
          <div className="flex flex-wrap max-w-6xl mx-auto px-4 py-2 relative">
            <div className="lg:flex-1">
              <Link href="/">
                <Image
                  src="/menu-logo.png"
                  alt="Treinador abner"
                  width={60}
                  height={60}
                  className="lg:w-[65px]"
                />
              </Link>
            </div>
            <Menu />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
