import './globals.css'
import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import "@fortawesome/fontawesome-svg-core/styles.css"; 
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false; 

export const metadata: Metadata = {
  title: 'Treinador Abner',
  description: 'Generated by create next app',
}

const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${ubuntu.className}`}>
      <body>{children}</body>
    </html>
  )
}
